### ISSUE TITLE
3. ödevin 3. cevabı hatalı

### ISSUE THREAD

**Issue by ardakyigit** [yourairman/PostgreSQL#1]
> --3 film tablosunda bulunan title sütunundaki film isimlerinden en az 4 adet büyük ya da küçük harf farketmesizin 'T' karakteri içeren film isimlerini sıralayınız.
> 
> **SELECT * FROM film WHERE title ILIKE '%t' OR title ILIKE 't%';**

Yukarıdaki sorgu, soruda istenen kriterleri karşılamıyor. Doğru sorgu aşağıdaki gibi olmalı.

**SELECT *
FROM film
WHERE title ILIKE '%T%T%T%T%';**

README.md buna göre güncellenebilir.

**Comment by yourairman** [comment]
Düzelttim teşekkür ederim...

**Comment by ardakyigit** [comment]
> SELECT * FROM film WHERE title ILIKE '%t' OR title ILIKE 't%t%t%t%';

Yine hatalı kalmış. Aşağıdaki gibi olmalı.

**SELECT * FROM film WHERE title ILIKE '%T%T%T%T%';**

Ek olarak, sadece **Patika_DB_dvdrental_Work3-LIKEandILIKE.sql** dosyasını değil de **README.md** dosyasını da güncellemek faydalı olabilir.

**Comment by yourairman** [comment]
:)  Dostum izlenimin çok iyi çok teşekkür ederim... Hemen düzeltiyorum
